
class ReCaptchaV2:
    def __init__(self, site_key):
        self.template = 'document.head.innerHTML="",document.body.innerHTML="",document.body.style.backgroundColor="#1c1e31";let script=document.createElement("script");script.src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit",script.async=!0,script.defer=!0;let title=document.createElement("title");title.innerText="Captcha Harvester";let txt=document.createElement("b");txt.id="txt",txt.style.color="white",txt.style.weight="white",txt.style.position="absolute";const node=document.createTextNode("Waiting for captcha");txt.appendChild(node),document.getElementsByTagName("body")[0].appendChild(txt),document.getElementById("txt").style.top="250px",document.getElementById("txt").style.left="175px";let captchaDiv=document.createElement("div");captchaDiv.position="absolute",captchaDiv.id="captcha-1",document.getElementsByTagName("head")[0].appendChild(title),document.getElementsByTagName("head")[0].appendChild(script),document.getElementsByTagName("body")[0].appendChild(captchaDiv);'
        self.invoke = 'function err(){(i=document.createElement("input")).setAttribute("type","hidden"),i.setAttribute("id","captchaResp"),i.setAttribute("value","error"),document.getElementsByTagName("body")[0].appendChild(i)}document.getElementById("txt").remove(),document.getElementById("captcha-1").style.position="absolute",document.getElementById("captcha-1").style.top="225px",document.getElementById("captcha-1").style.left="100px",grecaptcha.render("captcha-1",{sitekey:"%s",callback(e){(i=document.createElement("input")).setAttribute("type","hidden"),i.setAttribute("id","captchaResp"),i.setAttribute("value",e),document.getElementsByTagName("body")[0].appendChild(i)},"error-callback":"err"});' % site_key

class ReCaptchaV3:
    def __init__(self, site_key, action):
        self.template = 'document.head.innerHTML="",document.body.innerHTML="",document.body.style.backgroundColor="#1c1e31";let script=document.createElement("script");script.src="https://www.google.com/recaptcha/api.js?render=%s",script.async=!0,script.defer=!0;let title=document.createElement("title");title.innerText="Captcha Harvester";let txt=document.createElement("b");txt.id="txt",txt.style.color="white",txt.style.weight="white",txt.style.position="absolute";const node=document.createTextNode("Waiting for captcha");txt.appendChild(node),document.getElementsByTagName("body")[0].appendChild(txt),document.getElementById("txt").style.top="250px",document.getElementById("txt").style.left="175px",document.getElementsByTagName("head")[0].appendChild(title),document.getElementsByTagName("head")[0].appendChild(script);' % site_key
        self.invoke = 'grecaptcha.execute("%s",{action:"%s"}).then(function(e){(i=document.createElement("input")).setAttribute("type","hidden"),i.setAttribute("id","captchaResp"),i.setAttribute("value",e),document.getElementsByTagName("body")[0].appendChild(i)});' % (site_key, action)

class Hcaptcha:
    def __init__(self, site_key):
        self.template = 'document.head.innerHTML="",document.body.innerHTML="",document.body.style.backgroundColor="#1c1e31";let script=document.createElement("script");script.src="https://js.hcaptcha.com/1/api.js?render=explicit",script.async=!0,script.defer=!0;let title=document.createElement("title");title.innerText="Captcha Harvester";let txt=document.createElement("b");txt.id="txt",txt.style.color="white",txt.style.weight="white",txt.style.position="absolute";const node=document.createTextNode("Waiting for captcha...");txt.appendChild(node),document.getElementsByTagName("body")[0].appendChild(txt),document.getElementById("txt").style.top="250px",document.getElementById("txt").style.left="175px";let captchaDiv=document.createElement("div");captchaDiv.position="absolute",captchaDiv.id="captcha-1",document.getElementsByTagName("head")[0].appendChild(title),document.getElementsByTagName("head")[0].appendChild(script),document.getElementsByTagName("body")[0].appendChild(captchaDiv);' 
        self.invoke = 'function err(){(i=document.createElement("input")).setAttribute("type","hidden"),i.setAttribute("id","captchaResp"),i.setAttribute("value","error"),document.getElementsByTagName("body")[0].appendChild(i)}document.getElementById("txt").remove(),document.getElementById("captcha-1").style.position="absolute",document.getElementById("captcha-1").style.top="200px",document.getElementById("captcha-1").style.left="100px ",hcaptcha.render("captcha-1",{sitekey:"%s",callback(e){(i=document.createElement("input")).setAttribute("type","hidden"),i.setAttribute("id","captchaResp"),i.setAttribute("value",e),document.getElementsByTagName("body")[0].appendChild(i)},"error-callback":"err"});' % site_key